# Generated by Django 5.2.12 on 2026-03-31

import logbook.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('week_ending_date', models.DateField()),
                ('tasks_completed', models.TextField()),
                ('tasks_in_progress', models.TextField()),
                ('next_week_tasks', models.TextField()),
                ('challenges', models.TextField()),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skills_gained', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='logbook/attachments/', validators=[logbook.models.validate_log_attachment])),
                ('supervisor_comments', models.TextField(blank=True)),
                ('supervisor_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], max_length=20)),
                ('supervisor_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.placement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_weekly_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_logs',
                'ordering': ['-week_ending_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.UniqueConstraint(fields=('student', 'week_ending_date'), name='unique_weekly_log_student_week'),
        ),
        migrations.AddIndex(
            model_name='weeklylog',
            index=models.Index(fields=['student', 'week_ending_date'], name='weekly_logs_student_b27e01_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklylog',
            index=models.Index(fields=['placement', 'week_ending_date'], name='weekly_logs_placeme_497499_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklylog',
            index=models.Index(fields=['submission_status', 'review_status'], name='weekly_logs_submiss_421854_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklylog',
            index=models.Index(fields=['created_at'], name='weekly_logs_created_ceec25_idx'),
        ),
    ]
