# Generated by Django 5.2.5 on 2026-03-31 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='review_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('review_round', models.PositiveIntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_reviews', to=settings.AUTH_USER_MODEL)),
                ('weekly_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logbook.weeklylog')),
            ],
            options={
                'db_table': 'weekly_log_reviews',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['weekly_log', 'review_round'], name='weekly_log__weekly__754114_idx'), models.Index(fields=['supervisor', 'reviewed_at'], name='weekly_log__supervi_ac5c23_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLogAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submitted', 'Submitted'), ('review_started', 'Review Started'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], max_length=30)),
                ('previous_state', models.CharField(max_length=30)),
                ('new_state', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_log_actions', to=settings.AUTH_USER_MODEL)),
                ('weekly_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='logbook.weeklylog')),
            ],
            options={
                'db_table': 'weekly_log_audit_trail',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['weekly_log', 'created_at'], name='weekly_log__weekly__be6da1_idx'), models.Index(fields=['actor', 'created_at'], name='weekly_log__actor_i_b78a53_idx'), models.Index(fields=['action_type'], name='weekly_log__action__e86b9c_idx')],
            },
        ),
    ]
