# Generated by Django 5.2.5 on 2026-03-30 18:25

import django.db.models.deletion
import placements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('sub_county', models.CharField(blank=True, max_length=120)),
                ('parish', models.CharField(blank=True, max_length=120)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('full_address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'), models.Index(fields=['region', 'district'], name='organizatio_region_533493_idx'), models.Index(fields=['is_verified'], name='organizatio_is_veri_831d59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_letter', models.FileField(blank=True, null=True, upload_to='placements/letters/', validators=[placements.models.validate_pdf_file])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position_role', models.CharField(blank=True, max_length=140)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_mode', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=20)),
                ('submission_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised_placements', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_placements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='placements.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL)),
                ('workplace_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_supervised_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'submission_status'], name='placements_student_b22f15_idx'), models.Index(fields=['student', 'approval_status'], name='placements_student_67e4f7_idx'), models.Index(fields=['start_date', 'end_date'], name='placements_start_d_41bbd5_idx'), models.Index(fields=['created_at'], name='placements_created_02b7cd_idx')],
            },
        ),
    ]
