# Generated by Django 5.2.5 on 2026-03-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student Intern'), ('workplace_supervisor', 'Workplace Supervisor'), ('academic_supervisor', 'Academic Supervisor'), ('admin', 'Internship Administrator')], default='student', max_length=25),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(choices=[('staff', 'Staff'), ('senior', 'Senior Admin'), ('super', 'Super Admin')], default='staff', max_length=10)),
                ('department', models.CharField(blank=True, help_text='Administrative department', max_length=100)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='University registration number', max_length=50, unique=True)),
                ('institution', models.CharField(help_text='University or institution name', max_length=200)),
                ('faculty', models.CharField(blank=True, help_text='Faculty/School', max_length=200)),
                ('course', models.CharField(help_text='Course/Program of study', max_length=200)),
                ('year_of_study', models.PositiveIntegerField(help_text='Current year of study (1-6)')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('expected_graduation_year', models.PositiveIntegerField(help_text='Expected year of graduation')),
                ('internship_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='not_started', max_length=20)),
                ('profile_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_type', models.CharField(choices=[('workplace', 'Workplace Supervisor'), ('academic', 'Academic Supervisor')], help_text='Type of supervisor', max_length=20)),
                ('organization_name', models.CharField(help_text='Company or institution name', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Department/Unit', max_length=200)),
                ('position', models.CharField(help_text='Job title or position', max_length=100)),
                ('work_email', models.EmailField(blank=True, help_text='Work email (if different from user email)', max_length=254)),
                ('office_phone', models.CharField(blank=True, help_text='Office contact number', max_length=15)),
                ('specialization', models.CharField(blank=True, help_text='Area of expertise', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years in current role', null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Profile',
                'verbose_name_plural': 'Supervisor Profiles',
                'db_table': 'supervisor_profiles',
                'indexes': [models.Index(fields=['supervisor_type'], name='supervisor__supervi_f8af63_idx'), models.Index(fields=['organization_name'], name='supervisor__organiz_4f68bb_idx')],
            },
        ),
    ]
