# Generated by Django 5.2.5 on 2026-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_company_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Admin profile picture', null=True, upload_to='profiles/admins/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='profiles/students/'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Supervisor profile picture', null=True, upload_to='profiles/supervisors/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/users/'),
        ),
    ]
