# Generated by Django 5.2.5 on 2026-03-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_assign_placements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_manage_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Academic department', max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='disability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.PositiveIntegerField(blank=True, help_text='Current semester', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(blank=True, help_text='Alternative student number (if different from registration number)', max_length=50),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty/School (for academic supervisors)', max_length=200),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry sector for workplace supervisors', max_length=120),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Primary organization location', max_length=160),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='office_address',
            field=models.TextField(blank=True, help_text='Office address'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Type of organization (e.g. public, private, NGO)', max_length=100),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='work_phone',
            field=models.CharField(blank=True, help_text='Work phone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='other_names',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_level',
            field=models.CharField(choices=[('standard', 'Standard Admin'), ('staff', 'Standard Admin'), ('senior', 'Standard Admin'), ('super', 'Super Admin')], default='standard', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='internship_status',
            field=models.CharField(choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='not_assigned', max_length=20),
        ),
    ]
