# Generated by Django 5.2.5 on 2026-03-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminprofile_can_assign_placements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_approved',
            field=models.BooleanField(default=True, help_text='Set by admin for supervisor accounts after initial login'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login_completed',
            field=models.BooleanField(default=False, help_text='Tracks first successful login for supervisor approval workflow'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
