# Generated by Django 5.2.5 on 2026-03-31 21:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluation_criteria',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='evaluation__is_acti_b66331_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('general_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='placements.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='evaluations.evaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='evaluations.placementevaluation')),
            ],
            options={
                'db_table': 'evaluation_scores',
                'ordering': ['criterion__display_order', 'criterion__name'],
            },
        ),
        migrations.AddIndex(
            model_name='placementevaluation',
            index=models.Index(fields=['status'], name='placement_e_status_9ecf57_idx'),
        ),
        migrations.AddIndex(
            model_name='placementevaluation',
            index=models.Index(fields=['student', 'status'], name='placement_e_student_78b21b_idx'),
        ),
        migrations.AddIndex(
            model_name='placementevaluation',
            index=models.Index(fields=['evaluated_by', 'status'], name='placement_e_evaluat_8925ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_score_per_criterion'),
        ),
    ]
