# Generated by Django 5.2.5 on 2026-04-01 04:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_seed_default_criteria'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInternshipScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('supervisor_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('logbook_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('academic_weight', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4)),
                ('supervisor_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
                ('logbook_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('remarks', models.CharField(max_length=40)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_final_internship_scores', to=settings.AUTH_USER_MODEL)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_internship_score', to='placements.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_internship_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_internship_scores',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['grade'], name='final_inter_grade_247984_idx'), models.Index(fields=['final_score'], name='final_inter_final_s_e71220_idx'), models.Index(fields=['student'], name='final_inter_student_a7d110_idx')],
            },
        ),
    ]
