# Generated by Django 5.2.5 on 2026-04-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, help_text='Role of actor at time of action', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FINALIZE', 'Finalize'), ('COMPUTE', 'Compute')], max_length=20)),
                ('entity_type', models.CharField(choices=[('User', 'User'), ('Placement', 'Placement'), ('WeeklyLog', 'Weekly Log'), ('PlacementEvaluation', 'Evaluation'), ('FinalInternshipScore', 'Final Score')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_description', models.CharField(blank=True, help_text='Human-readable description of the entity', max_length=255)),
                ('previous_value', models.JSONField(blank=True, help_text='Previous state before change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state after change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client info')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-action_time'],
                'indexes': [models.Index(fields=['actor', '-action_time'], name='audit_logs_actor_i_12201e_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['-action_time'], name='audit_logs_action__588e63_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('reference_type', models.CharField(blank=True, choices=[('Placement', 'Placement'), ('WeeklyLog', 'Weekly Log'), ('PlacementEvaluation', 'Evaluation'), ('FinalInternshipScore', 'Final Score')], max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
    ]
